blank_issues_enabled: false
contact_links:
  - name: Community Discussions & Questions
    url: https://github.com/naenmad/Beberes/discussions
    about: Ask questions, share ideas, and connect with other Beberes users.
